//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПРАКТИЧЕСКАЯ_4
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViborUslugi
    {
        public int Id { get; set; }
        public string Nameusluga { get; set; }
        public string Timework { get; set; }
        public string Price { get; set; }
        public string Usluga { get; set; }
    }
}
